import { useMemo, useState } from 'react'
import { KeyRound, LockKeyhole, TriangleAlert } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'

function LoginPanel() {
  const navigate = useNavigate()
  const { signIn } = useAuth()
  const [tokenInput, setTokenInput] = useState('')
  const [error, setError] = useState('')
  const [submitting, setSubmitting] = useState(false)

  const tokenPreview = useMemo(() => {
    if (!tokenInput.trim()) {
      return 'Paste the faculty-issued JWT to unlock the portal.'
    }

    const parts = tokenInput.trim().split('.')

    if (parts.length !== 3) {
      return 'JWT format should look like header.payload.signature.'
    }

    return 'Token structure looks valid. The claims will be parsed locally before the portal opens.'
  }, [tokenInput])

  const handleSubmit = async (event) => {
    event.preventDefault()
    setSubmitting(true)
    setError('')

    try {
      signIn(tokenInput)
      navigate('/app/dashboard', { replace: true })
    } catch (nextError) {
      setError(nextError.message)
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <section className="glass-panel w-full rounded-[32px] p-6 sm:p-8">
      <div className="mb-8">
        <div className="mb-4 inline-flex rounded-2xl border border-white/10 bg-white/5 p-3 text-cyan-300">
          <LockKeyhole className="h-6 w-6" />
        </div>
        <h2 className="text-3xl font-semibold text-slate-100">Access the interview terminal</h2>
        <p className="mt-3 max-w-lg text-sm leading-7 text-slate-300/74">
          The portal accepts a signed JWT generated by your faculty or admin workflow. No candidate profile data is stored
          permanently in this client.
        </p>
      </div>

      <form className="space-y-5" onSubmit={handleSubmit}>
        <label className="block space-y-3">
          <span className="font-mono text-xs uppercase tracking-[0.32em] text-slate-300/60">Candidate access token</span>
          <textarea
            value={tokenInput}
            onChange={(event) => setTokenInput(event.target.value)}
            placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
            className="min-h-40 w-full rounded-[24px] border border-white/10 bg-carbon-900/80 px-4 py-4 font-mono text-sm leading-7 text-slate-100 outline-none transition placeholder:text-slate-400/40 focus:border-cyan-300/40"
            required
          />
        </label>

        <div className="rounded-[24px] border border-white/8 bg-white/4 px-4 py-4">
          <div className="flex items-start gap-3">
            <KeyRound className="mt-0.5 h-4 w-4 text-cyan-300" />
            <p className="text-sm leading-7 text-slate-300/76">{tokenPreview}</p>
          </div>
        </div>

        {error ? (
          <div className="rounded-[24px] border border-rose-400/24 bg-rose-500/10 px-4 py-4 text-sm text-rose-200">
            <div className="flex items-start gap-3">
              <TriangleAlert className="mt-0.5 h-4 w-4" />
              <span>{error}</span>
            </div>
          </div>
        ) : null}

        <button
          type="submit"
          disabled={submitting}
          className="inline-flex w-full items-center justify-center gap-2 rounded-[24px] bg-cyan-300 px-5 py-4 text-sm font-semibold text-slate-950 transition hover:bg-cyan-200 disabled:cursor-not-allowed disabled:bg-cyan-300/70"
        >
          <LockKeyhole className="h-4 w-4" />
          {submitting ? 'Validating token...' : 'Enter secure portal'}
        </button>
      </form>
    </section>
  )
}

export default LoginPanel
